name: Provenance Capsule Sync Validator

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check vaultghost_embed.md presence
        run: |
          if [ ! -f vaultghost_embed.md ]; then
            echo "::error ::Missing VaultGhost embed"
            exit 1
          fi

      - name: Validate JSON
        run: |
          jq . c2pa-manifest.json || exit 1
